### PR TITLE
Update bs4 to 4.6.0 and split ST2 and ST3 versions

### PR DESCRIPTION
**Pull request by deathaxe**
This PR updates beautifulsoup to version 4.6.0 from https://pypi.python.org/pypi/beautifulsoup4
This release requires to provide different versions for python2 and python3.
Therefore the sub directory all is replaced by ST2 and ST3.

### CODE REVIEW

**Comment by jlegewie** [comment]
Thanks for the PR. I haven't used this myself for a while and won't have the time to test whether it works. Did you test it thoroughly and can I safely merge it?

**Comment by deathaxe** [comment]
I have been using bs4 4.6.0 for a while now, when it started to complain about python3 incompatibilities since ST 3143. Therefore I checked out the latest releases from pypi to split python2 and 3 branches.

It was installed by MarkdownLivePreview package on my WinPC, which runs normal afterwards.

mdpopups makes use of bs4, too, if it is available and never complained about anything.

Do you know any other packages using it, which might be worth checking?

**Comment by deathaxe** [comment]
Created a fixup! as I accidentally placed the bs4 files directly under st3 folder before.

Corrected that and checked functionality with

- MarkdownTOC
- xpath
- Exalt

**Comment by jlegewie** [comment]
Great. Merging now... Thanks.

**Comment by deathaxe** [comment]
Remark: You could have squashed the commits so the fixup! would have been gone.

Thanks anyway.

**Pull request merged**
